# Generated by Django 2.2 on 2020-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFSM', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
