# Generated by Django 2.2 on 2020-07-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFSM', '0003_nl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NL',
        ),
    ]
